#include <QApplication>
#include <QGraphicsView>
#include <QWheelEvent>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsWidget>
#include <QPropertyAnimation>
#include <QGraphicsSimpleTextItem>
#include <QGraphicsDropShadowEffect>
#include <QMenu>
#include <QAction> 
#include <QDebug>